/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import beans.Prodavac;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jms.Destination;
import javax.jms.JMSConsumer;
import javax.jms.JMSContext;
import javax.jms.JMSException;
import javax.jms.JMSProducer;
import javax.jms.Message;
import javax.jms.ObjectMessage;
import utils.Helpers;
import utils.TipZahteva;
import beans.*;

/**
 *
 * @author malenicn
 */
public class ApartmanIzmena extends javax.swing.JFrame {
    
    private Apartman a;

    /**
     * Creates new form ApartmanUnos
     */
    public ApartmanIzmena(Apartman a) {
        this.a = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ime = new javax.swing.JTextField();
        drzava = new javax.swing.JTextField();
        grad = new javax.swing.JTextField();
        ulica = new javax.swing.JTextField();
        opis = new javax.swing.JTextField();
        broj = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        
        ime.setText(a.getIme());
        drzava.setText(a.getAdresa().getDrzava());
        grad.setText(a.getAdresa().getGrad());
        ulica.setText(a.getAdresa().getUlica());
        opis.setText(a.getAdresa().getOpis());
        broj.setValue(a.getAdresa().getBroj());
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closingHandler(evt);
            }
        });
        
        jLabel1.setText("Ime:");
        
        jLabel2.setText("Drzava:");
        
        jLabel3.setText("Grad:");
        
        jLabel4.setText("Ulica:");
        
        jLabel5.setText("Broj:");
        
        jLabel6.setText("Opis:");
        
        ime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeActionPerformed(evt);
            }
        });
        
        jButton1.setText("Unesi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        status.setText("");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jButton1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ulica)
                                                        .addComponent(opis)
                                                        .addComponent(grad)
                                                        .addComponent(drzava)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(broj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 334, Short.MAX_VALUE))
                                                        .addComponent(ime))
                                                .addGap(58, 58, 58))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(status)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(drzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(ulica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(opis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(broj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(status))
                                .addContainerGap(105, Short.MAX_VALUE))
        );
        
        pack();
    }// </editor-fold>                        

    private void imeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Apartman aNovi = new Apartman();
        aNovi.setId(a.getId());
        aNovi.setProdavac(a.getProdavac());
        
        aNovi.setIme(ime.getText());
        Adresa adr = new Adresa();
        adr.setId(a.getAdresa().getId());
        
        try {
            broj.commitEdit();
        } catch (java.text.ParseException e) {
        }
        Number n = (Number) broj.getValue();
        adr.setBroj(n.longValue());
        
        adr.setDrzava(drzava.getText());
        adr.setGrad(grad.getText());
        adr.setOpis(opis.getText());
        adr.setUlica(ulica.getText());
        
        aNovi.setAdresa(adr);
        adr.setApartman(aNovi);
        
        JMSContext context = prodavac.Prodavac.connectionFactory.createContext();
        
        Destination destination = prodavac.Prodavac.zahtevi;
        
        JMSConsumer consumer = context.createConsumer(prodavac.Prodavac.odgovori, Helpers.getId(prodavac.Prodavac.prodavac.getUsername(),
                prodavac.Prodavac.prodavac.getPassword()));
        JMSProducer producer = context.createProducer();
        
        ObjectMessage zahtev = context.createObjectMessage();
        try {
            zahtev.setStringProperty("id", prodavac.Prodavac.prodavac.getUsername()
                    + prodavac.Prodavac.prodavac.getPassword());
            zahtev.setStringProperty("username", prodavac.Prodavac.prodavac.getUsername());
            zahtev.setStringProperty("password", prodavac.Prodavac.prodavac.getPassword());
            
            zahtev.setObject(aNovi);
            zahtev.setIntProperty("tip", TipZahteva.IZMENA_APARTMANA.ordinal());
            
            producer.send(destination, zahtev);
        } catch (JMSException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Message odgovor = consumer.receive();
        if (odgovor instanceof ObjectMessage) {
            
            try {
                Object objekat = ((ObjectMessage) odgovor).getObject();
                if (objekat != null) {
                    status.setText("Success");
                    
                    a.setIme(ime.getText());
                    Adresa adrUpdate = a.getAdresa();
                    adrUpdate.setBroj(adr.getBroj());
                    adrUpdate.setDrzava(drzava.getText());
                    adrUpdate.setGrad(grad.getText());
                    adrUpdate.setOpis(opis.getText());
                    adrUpdate.setUlica(ulica.getText());
                } else {
                    status.setText("Error");
                }
            } catch (JMSException ex) {
                Logger.getLogger(PromenaKorisnickihPodataka.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            jLabel3.setText("Greska u komunikaciji - odgovor Posrednika nije tipa TextMessage");
        }
    }
    
    private void closingHandler(java.awt.event.WindowEvent evt) {
        prodavac.Prodavac.apartmaniPanel.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartmanUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartmanUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartmanUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartmanUnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApartmanUnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JSpinner broj;
    private javax.swing.JTextField drzava;
    private javax.swing.JTextField grad;
    private javax.swing.JTextField ime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField opis;
    private javax.swing.JLabel status;
    private javax.swing.JTextField ulica;
    // End of variables declaration                   
}
